name: Release Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true
      upload:
        description: 'Upload: If want ignore'
        required: false
      publish:
        description: 'Publish: If want ignore'
        required: false
      play:
        description: 'Play: If want ignore'
        required: false

jobs:
  libcore:
    name: Native Build (LibCore)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Calculate Golang Status
        run: |
          find buildScript libcore/*.sh | xargs cat | sha1sum > golang_status

      - name: Calculate Libcore Status
        run: |
          git ls-files libcore | xargs cat | sha1sum > libcore_status

      - name: Cache LibCore
        id: cache
        uses: actions/cache@v3
        with:
          path: app/libs/libcore.aar
          key: ${{ hashFiles('.github/workflows/*', 'golang_status', 'libcore_status') }}

      - name: Install Golang
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/setup-go@v3
        with:
          go-version: ^1.21

      - name: Execute Native Build
        if: steps.cache.outputs.cache-hit != 'true'
        run: ./run lib core

      - name: Upload Library
        uses: actions/upload-artifact@v3
        with:
          name: libcore.aar
          path: app/libs/libcore.aar